### ISSUE TITLE
sched_yield unfinished / resumed

### ISSUE THREAD

**Issue by ifelsefi** [Byron/dua-cli#101]
Hello

I am running dua on a file system of several petabytes.  It is taking longer than expected.  `strace` shows repeating message:

```
[pid 165083] sched_yield( <unfinished ...>
[pid 165082] sched_yield( <unfinished ...>
[pid 165073] sched_yield( <unfinished ...>
[pid 165072] <... sched_yield resumed> ) = 0
[pid 165071] <... sched_yield resumed> ) = 0
[pid 165068] sched_yield( <unfinished ...>
[pid 165066] <... sched_yield resumed> ) = 0
[pid 165063] sched_yield( <unfinished ...>
[pid 165061] <... sched_yield resumed> ) = 0
[pid 165056] sched_yield( <unfinished ...>
[pid 165085] sched_yield( <unfinished ...>
[pid 165084] <... sched_yield resumed> ) = 0
[pid 165083] <... sched_yield resumed> ) = 0
[pid 165082] <... sched_yield resumed> ) = 0
[pid 165073] <... sched_yield resumed> ) = 0
[pid 165072] sched_yield( <unfinished ...>
[pid 165071] sched_yield( <unfinished ...>
[pid 165068] <... sched_yield resumed> ) = 0
[pid 165066] sched_yield( <unfinished ...>
[pid 165063] <... sched_yield resumed> ) = 0
[pid 165061] sched_yield( <unfinished ...>
[pid 165056] <... sched_yield resumed> ) = 0
[pid 165085] <... sched_yield resumed> ) = 0
[pid 165084] sched_yield( <unfinished ...>
[pid 165083] sched_yield( <unfinished ...>
```

Have you run into this issue before? 

dua shows this then does not proceed further:

```
[user@node ~]$ time /opt/dua/2.14.4/dua -x --format bytes /data
Enumerating 4520023 entries
```

The binary was downloaded from Github not built from source.

The servers running dua have 16 core CPUs, a lot of memory, and we are checking a fast network storage system. 

Thank you,
Doug

**Comment by Byron** [comment]
Thanks for letting me know! It's the first time I see this and from dua's point of view it shouldn't matter how big the storage to crawl is as long as there is enough memory to hold the tree.

Maybe try to run it with a single thread only (`dua -t 1 …`) to see if that changes things to the better.

**Comment by ifelsefi** [comment]
Hello

I will close.   Another staff member was copying over several hundred TB while I was running dua :)

I love dua.  It's so fast.  Thanks for making this happen!

**Comment by Byron** [comment]
That's great to hear, thanks for letting me know! It's interesting to see how `dua` responds if folders are changing while iterating them - I think it just ignores traversal errors right now, maybe there could be better reporting on it.

https://github.com/Byron/dua-cli/blob/4598d64a1150967e48013091e044eae851de62f9/src/interactive/widgets/main.rs#L40-L46

The `..` indicates that it's actually ignoring `io_errors` field and as far as I can tell it's displayed nowhere. There is an option to display statistics, but not in interactive mode and also they don't contain IO errors.

Looks like the error reporting story could definitely be improved on.


Besides, I am quite amazed by the amount of data you handle and that this is fast even :D - the only thing I new were slow network drives that usually woudln't given more than 30MB/s if you were lucky, a decade ago.

**Comment by ifelsefi** [comment]
Yeah, I work in HPC and we have some fast storage / networks. 

```
admin-dduckwor@hre-cn0007[~]$ time /opt/dua/2.14.4/dua -x /vast/data
   1.93 PB /vast/data

real    8m3.947s
user    24m58.074s
sys     21m18.614s
```

This is a great tool so thank you!
