### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Fujiwara-Chika** [Byron/dua-cli#123]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/44722787/167297746-f6cedb9b-8cfa-4100-b809-fc014bfb6f9e.png">

**Comment by Byron** [comment]
Thanks for the hint. The installer is broken and I adjusted the README for a fix.

It's strange that the intel darwin binary isn't working though.
