### ISSUE TITLE
Latest release doesn't have binaries for all platforms

### ISSUE THREAD

**Issue by dufferzafar** [Byron/dua-cli#134]
The latest release doesn't have binaries for all platforms: https://github.com/Byron/dua-cli/releases/tag/v2.17.8

It only has Windows!

**Comment by Byron** [comment]
[CI had problems](https://github.com/Byron/dua-cli/actions/runs/2614312415) and I have restarted the failing tasks in the hopes the runners come up.

That should add the missing binaries.
