### ISSUE TITLE
Couldn't auto-configure correct amount of threads for Apple M2

### ISSUE THREAD

**Issue by fmckeogh** [Byron/dua-cli#135]
I get this message when running on my M2 Air. Just opening this issue for tracking, I'll start on a fix now:)

**Comment by Byron** [comment]
Hehe, yes, please, I am looking forward to the contribution :)!
From my experience, 4 threads is the best value, but maybe that changed. `hyperfine` might be useful to determine a good value, like `hyperfine "dua -t4" "dua t5"`.
