### ISSUE TITLE
Seems like `-x` doesn't work with rclone fuse mounts?

### ISSUE THREAD

**Issue by colemickens** [Byron/dua-cli#138]
I'm having a hard time telling what's going on, but it seems like dua is still crossing FS boundaries and trying to enumerate huge rclone shares when I use `-x`.

**Comment by Byron** [comment]
Thanks for reporting. It all comes down to the device id [as it's compared](https://github.com/Byron/dua-cli/blob/5a11216b53af2644100fcfebe44b0b6eea2dbb78/src/crossdev.rs#L11) to the device ID [of the root path of the traversal](https://github.com/Byron/dua-cli/blob/75b3eed98f14d918f474f73caa3cdedd5af927ad/src/aggregate.rs#L91).

Maybe you can experiment more with these to learn what these are. Ultimately I expect them to be the same, even though they probably shouldn't be.

**Comment by krallin** [comment]
I suspect you probably hit the same issue I did: https://github.com/Byron/dua-cli/pull/146

**Comment by Byron** [comment]
Indeed, I believe this is fixed [in the latest release](https://github.com/Byron/dua-cli/pull/146). Please let us know if it's not the case though.
