### ISSUE TITLE
Support sorting by mtime

### ISSUE THREAD

**Issue by SUPERCILEX** [Byron/dua-cli#141]
It'd be nice to be able to sort by oldest modified files/directories.

**Comment by Byron** [comment]
Could you define this enhancement more so it could be implemented by a contributor? Where does it apply? Which flags to use, etc… . Thanks

**Comment by SUPERCILEX** [comment]
This is in interactive mode. Instead of just being able to sort by file/directory size, you should be able to sort by last modified time. Ncdu uses the M shortcut: https://dev.yorhel.nl/ncdu/man2#:~:text=Order%20by%20latest%20child%20mtime%2C%20or%20modified%20time.%20(press%20again%20for%20descending%20order)%20Requires%20the%20%2De%20flag.

**Comment by Byron** [comment]
Good catch!
