### ISSUE TITLE
Output not refreshing since v2.18

### ISSUE THREAD

**Issue by multimeric** [Byron/dua-cli#143]
I installed `dua` on my Linux computing cluster, which I access via `ssh` on my iTerm terminal. Version v2.17.8 runs perfectly, but all newer versions (I've tested 2.19.0 and 2.18.2) fail to actually refresh the terminal unless the user interacts using the keyboard. For example, the application opens with a blank screen, and pressing up on the keyboard will cause the TUI to show, but then the scanned files count doesn't update until I press another button on the keyboard. It simply won't refresh by itself. Did you bump one of the terminal rendering libraries or adjust the rendering behaviour with the move to v2.18.x? Happy to provide more info to help diagnose this.

**Comment by Byron** [comment]
Thanks for bringing this up - I can reproduce it as well and would love your help to diagnose the source of the problem. I agree that it either is due to a change in this codebase, or to changes in `jwalk` or `crossterm`.

**Comment by multimeric** [comment]
Is it `crossterm`, or `termion` that's used on Linux?

**Comment by Byron** [comment]
It uses `crossterm` for everything, `termion` (to me) is unmaintained and I am phasing it out.

**Comment by multimeric** [comment]
Okay, I tried to recreate this on my own Ubuntu machine using the GNOME termial, but it works fine, even through `ssh`. I'm wondering if it's specific to the iTerm2 + Linux combination.

**Comment by Byron** [comment]
That's interesting - I can reproduce it with Alacritty on MacOS and crossterm. I'd think this should be unrelated to the terminal used, but validating that should be straightforward. But maybe you already validated it by running the same binary which exhibited inconsistent behaviour depending on the runtime environment?

**Comment by multimeric** [comment]
I'm not sure what you're asking me to do.

**Comment by Byron** [comment]
Can you run the binary from the compute cluster that exhibits incorrect behaviour in the other runtime environment where *a* `dua` binary showed the correct behaviour? That way it would be clear that it's not the binary itself that's causing the refresh issue, but is something related to the runtime environment (maybe the terminal). 
I would be surprised if the terminal plays a role there, but who knows.

**Comment by multimeric** [comment]
Well I downloaded the exactly same binary from the github releases page onto my Ubuntu laptop and onto the computing cluster. It worked only on my laptop. This suggests to me that it must be environment related.

**Comment by Byron** [comment]
Thanks for the update. It's related to the version as well, so either it's a code update in `dua` or it's a dependency update that ultimately causes this. Since `dua` is in maintenance mode with no new features, I presume it's a dependency update that caused this.

**Comment by multimeric** [comment]
Okay I tested this out with `git bisect` (finally a chance to use it!), and I got:
```
28f5ac90cc1ba7d668ae8a83eb5cd899294a8301 is the first bad commit
commit 28f5ac90cc1ba7d668ae8a83eb5cd899294a8301
Author: Sebastian Thiel <sebastian.thiel@icloud.com>
Date:   Mon Sep 12 09:45:50 2022 +0800

    feat: Automatically resize if the terminal changes in size. (#28)

 Cargo.lock                                        |  4 ---
 src/interactive/app/eventloop.rs                  | 30 ++++++++++++-----------
 src/interactive/app/tests/journeys_with_writes.rs |  8 +++---
 src/interactive/app/tests/utils.rs                |  8 ++++--
 4 files changed, 25 insertions(+), 25 deletions(-)
```

**Comment by multimeric** [comment]
It's quite a small commit (although it seems to bump both `crosstermion` and `tui-react`). So hopefully it's not too hard to work out what happened?

**Comment by Byron** [comment]
Thanks a lot for researching this! Indeed, `git bisect` can be very handy!

It's definitely a dependency bump along with some changes to make it compile, but no functional changes on top of that.
That's not the clear pointer I was hoping for, but a start.
