### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by todd1794** [Byron/dua-cli#148]
I am running 2.17.5 on an old machine and it is MUCH faster than the 2.19.2 I just installed today. I understand this is not much info but I wanted to submit this before I forgot. I can flesh this out if helpful.

Thanks

Todd

**Comment by Byron** [comment]
Thanks for letting me know! Can you provide more information to help reproduce this? The invocation would be useful to start.

You can also try to set the amount of threads explicitly, maybe something changed around that?
Thank you

**Comment by todd1794** [comment]
False alarm. Gotta go apples to apples.

```root@rescue ~ # sync; echo 1 > /proc/sys/vm/drop_caches
root@rescue ~ # sync; echo 2 > /proc/sys/vm/drop_caches
root@rescue ~ # sync; echo 3 > /proc/sys/vm/drop_caches
root@rescue ~ # time dua_2.19.2 i /data

real    6m23.985s
user    3m44.412s
sys     4m3.708s
root@rescue ~ # sync; echo 1 > /proc/sys/vm/drop_caches
root@rescue ~ # sync; echo 2 > /proc/sys/vm/drop_caches
root@rescue ~ # sync; echo 3 > /proc/sys/vm/drop_caches
root@rescue ~ # time dua_2.17.5 i /data

real    6m33.963s
user    4m44.368s
sys     5m2.561s```

the filesystem has around 7 millions files added up to 43TB.

Thank you for such a wonderful tool! I use it all the time.

Todd

**Comment by Byron** [comment]
Thanks a lot! So it does look like the new version is using significantly more system resources, even though in the end it ends up being more or less in the same ballpark.

It's probably alright, but please let me know if there is anything else to do here.

PS: You might like [PDU](https://crates.io/crates/parallel-disk-usage)
