### ISSUE TITLE
Replace tui with ratatui

### ISSUE THREAD

**Issue by auronandace** [Byron/dua-cli#161]
I noticed you have `tui` as a dependency and it has not been maintained for quite a while now.

Here is a drop-in alternative that may be useful: https://github.com/tui-rs-revival/ratatui

It seems to be all development has now shifted to `ratatui` as a successor to the very popular `tui` crate.

**Comment by Byron** [comment]
Thanks for letting me know and I will keep this in mind in case `tui` one day breaks. Until that day, I am happy with `tui` particularly because it doesn't change, reducing my maintenance burden.
Thanks for your understanding.
