### ISSUE TITLE
Output layout difference between macOS build and linux build

### ISSUE THREAD

**Issue by chenrui333** [Byron/dua-cli#163]
While [upgrading dua-cli formula](https://github.com/Homebrew/homebrew-core/pull/130262), we found the output is different between macOS build and linux build.

Below is the difference
```diff
  -\e[32m      0  B\e[39m /tmp/dua-cli-test-20230505-13568-dbxcir/empty.txt
  -\e[32m      2  B\e[39m /tmp/dua-cli-test-20230505-13568-dbxcir/file.txt
  -\e[32m      2  B\e[39m total
  +\e[32m     0   B\e[39m /tmp/dua-cli-test-20230505-13568-dbxcir/empty.txt
  +\e[32m     2   B\e[39m /tmp/dua-cli-test-20230505-13568-dbxcir/file.txt
  +\e[32m     2   B\e[39m total
```

**Comment by Byron** [comment]
This is the result of a [sneaky breaking change](https://github.com/Byron/dua-cli/commit/3ccf204a18c784a7af7b6255173b332e0083c047) that aims to be a fix.

Would you prefer to revert it here and get it introduced with [the next version version](https://github.com/Byron/dua-cli/pull/158)?

**Comment by chenrui333** [comment]
> Would you prefer to revert it here

what do you mean by `revert it here`?

**Comment by Byron** [comment]
[This change](https://github.com/Byron/dua-cli/commit/3ccf204a18c784a7af7b6255173b332e0083c047) is responsible for the breakage you are experiencing. Revert it now, but get the change in the next breaking release which is already lined up? 
Or adjust the test's expectations now and I leave it as is. The test will need to change sooner or later.

**Comment by chenrui333** [comment]
Got you, I am gonna adjust the test for now then. Thanks!
