### ISSUE TITLE
alignment off when in interactive mode and -f binary

### ISSUE THREAD

**Issue by tessus** [Byron/dua-cli#167]
```
│  2.43 GiB |   0.8%  ▏         |  .gradle                                                                                                                                                     │
│1010.36 MiB |   0.3%            |  .yarn                                                                                                                                                      │
│807.69 MiB |   0.3%            |  .npm-global                                                                                                                                                 │
│412.85 MiB |   0.1%            |  .vscode                                                                                                                                                     │
```

I think when using `-f binary` the left column must be one character wider, because the max number value is 1024 and thus won't change units (start at 0 again) after 999.99.

**Comment by Byron** [comment]
I have trouble reproducing it. Can you validate you are using the latest published version (v2.20.1)?

**Comment by tessus** [comment]
Yep, I an sure:

<img width="488" alt="image" src="https://github.com/Byron/dua-cli/assets/223439/9137ed13-dcb5-4038-b0de-0517ce8fec4f">

**Comment by QuentinMoss** [comment]
I can take a look at this one @Byron

**Comment by QuentinMoss** [comment]
@Byron I'm not able to reproduce this on OS X or Pop_OS.

**Comment by tessus** [comment]
It's a weird situation and not easy to reproduce. I created a single file with 1059439247 bytes in a directory. I can't reproduce it with that file either.

But with a `.yarn` directory with many folders and files totalling 1059439247 bytes, the issue manifests itself.

Here is a compressed version. I used the highest compression rate, but it's still 710MB:
https://evermeet.cx/pub/tmp/yarn.7z

Uncompress it in a subdirectory and run `dua -f binary i` in the folder above.

**Comment by tessus** [comment]
Wait. A few less bytes will also do:

```
mkfile 1059438592 hello.file
```

**Comment by QuentinMoss** [comment]
There's definitely some alignment off when using interactive:
<img width="2503" alt="Screenshot 2023-07-06 at 10 33 50 PM" src="https://github.com/Byron/dua-cli/assets/350409/8c6d9dfd-32fe-4a0b-a15f-e0ea7f313d6d">

**Comment by tessus** [comment]
Also in non-interactive mode:

```
$ dua
  4.00 KiB .editorconfig
  4.00 KiB .gitignore
  4.00 KiB Cargo.toml
  4.00 KiB LICENSE
  4.00 KiB Makefile
  4.00 KiB etc
  8.00 KiB README.md
 12.00 KiB ci
 16.00 KiB .github
 32.00 KiB Cargo.lock
172.00 KiB CHANGELOG.md
188.00 KiB src
  1.32 MiB tests
  1.81 MiB .git
725.04 MiB yarn.7z
844.68 MiB target
1010.36 MiB .yarn
1015.69 MiB .test2
  1.00 GiB .test
  1.92 GiB test_file2
  6.44 GiB total
```

**Comment by nyurik** [comment]
I have encountered it too:

```plain
│  1.03 GiB |   1.4%  ▏         | /osmpbf
│  1.00 GiB |   1.4%  ▏         | /crates.io
│1001.06 MiB |   1.4%  ▏         | /sqlite-hashes
```
