### ISSUE TITLE
Scanning stucks on macOS 14.0

### ISSUE THREAD

**Issue by liebkne** [Byron/dua-cli#173]
After I updated macOS to 14.0, scanning stuck soon after started. How can I debug this? Thanks.

<img width="967" alt="image" src="https://github.com/Byron/dua-cli/assets/5475262/d3bcf063-42ea-4491-9716-f11f193098e0">

**Comment by Byron** [comment]
It's strange and I have not encountered that before. You could try different command-line flags to alter if it crosses filesystems. Threads could be changed so only a single thread is used, and when that gets stuck the activity monitor can show opened files - maybe that shows what blocks it.

In general, `dua` can only get stuck if the filesystem blocks forever/a long time when getting file metadata.

**Comment by liebkne** [comment]
Hi, I tried `dua -t 1 i` and saw it get stuck at `.orbstack`. Then I tried `dua -t 1 -i .orbstack i` and saw it get stuck at `.cargo`... Then `dua -t 1 -i .orbstack -i .cargo i` and it still get stucks...

**Comment by Byron** [comment]
Interesting - both work for me.

What do other tools do? I'd expect them to get stuck as well.

**Comment by liebkne** [comment]
Hi, I tried `dust`, `erdtree` and GUI tools like `DaisyDisk.app`, all work fine.

**Comment by Byron** [comment]
That's really interesting - `dua` does't do anything special, just `symlink_metadata()` calls on paths. With `-t` multi-threading goes away as well so that can't be a source of deadlocking either. I assume this truly is 'blocking' behaviour, right? That is, there is no high-CPU observable?

**Comment by liebkne** [comment]
> That is, there is no high-CPU observable?

Yes.

I reinstall everything (`dua, `rust` etc.`) and reboot many times... And the issue is now gone. Not sure what was happened...I'm going to close the issue now. Thanks for your help!
