### ISSUE TITLE
Test fails on 32-bit targets

### ISSUE THREAD

**Issue by cinerea0** [Byron/dua-cli#197]
When running tests on an i686 target, the following failure occurs:

```
---- traverse::tests::size_of_entry_data stdout ----
thread 'traverse::tests::size_of_entry_data' panicked at src/traverse.rs:315:9:
assertion `left == right` failed: the size of this should not change unexpectedly as it affects overall memory consumption
  left: 56
 right: 80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This failure can be seen in CI [here](https://github.com/void-linux/void-packages/actions/runs/7171417083/job/19526367908?pr=47626).

Reading the assertion message, is it necessary that the size of the data be exactly 80, or just that it be less than or equal to 80?

**Comment by Byron** [comment]
Indeed, the structure shouldn't get larger without confirmation, but it can always get smaller :).
A fix would definitely be welcome!
