### ISSUE TITLE
error[E0446]: crate-private type `FilesystemScan` in public interface

### ISSUE THREAD

**Issue by Cellesti** [Byron/dua-cli#226]
Hi, since dua-cli v2.27.0, i receive this error while compiling:
```
error[E0446]: crate-private type `FilesystemScan` in public interface
  --> src/interactive/app/state.rs:42:5
   |
27 | pub(crate) struct FilesystemScan {
   | -------------------------------- `FilesystemScan` declared as crate-private
...
42 |     pub scan: Option<FilesystemScan>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type
```

I am on Alpine Linux which is still using Rust 1.72.1 (due to some issues with newer Rust on 32-bit ARM).

I think that is probably the cause of the problem, so may i know if Rust 1.72.1 is still supported by dua-cli?

Thanks.

**Comment by Byron** [comment]
Thanks for reporting!

As I always build applications with the latest compiler, as is done by CI, these kinds of issues won't be typically noticed.
However, please feel free to submit a PR or patch for this once you have confirmed it to be working for you, and it will be merged.
Thanks for your help.

**Comment by Byron** [comment]
Turning `pub(crate) struct FilesystemScan {` into `pub struct FilesystemScan {` should already do the trick, in case that's easy for you to try.

**Comment by Byron** [comment]
Great! Shouldn't happen in the next release, even though it might happen again.
