### ISSUE TITLE
Provide option for not following symlinks

### ISSUE THREAD

**Issue by crides** [Byron/dua-cli#24]
This just happened today so I think I should bring this up.

Basically there's a folder that contains a ton of trash, but also happened to point to another important folder and I didn't know about that. So when I went ahead and cleaned up the first folder with the interactive mode, it also deletes the second one.

So I wonder if an option can be added so that symlinks are not followed (or even make that the default behaviour) so things like this won't happen to other people as well.

**Comment by Byron-TW** [comment]
I am very sorry to hear that dua did indeed eat your laundry :(! What an oversight, and clearly a result of me being sloppy and trying to save time by not writing crucial tests.

Please update to the latest version, v2.1.8, which doesn't follow symbolic links to directories anymore.

**Comment by vks** [comment]
I believe there is still something wrong, as I just had dua delete files I did not intend to delete.

**Comment by crides** [comment]
Can you provide more details? Are the files you don't want to delete also symlinks to folders/files?

**Comment by Byron-TW** [comment]
@vks I absolutely agree, `dua` must not follow symlinks when deleting files. However, this was fixed in the latest version, and thus it's most important for us to learn which version you were effectively using. If that is indeed the latest one, I would hope you can provide a reproducible example so this (possibly new) issue can be fixed ASAP.
Thank you.

**Comment by vks** [comment]
I was using a very recent version from my pull request yesterday (3baf7f31b91c71ba0acb2be886a47ccbd2b295fb plus updated dependencies).

I still need to investigate what exactly happened and whether I can reproduce it, but `dua` certainly deleted many more files than I marked. I suspect it is related to symlinks, but I could be something else.

**Comment by vks** [comment]
After further investigation, I don't think that this was ever fixed correctly. Currently, `dua` uses `path.metadata()` when deleting recursively, for which `is_symlink` [always returns `false`](https://doc.rust-lang.org/std/fs/struct.FileType.html#method.is_symlink)! `std::fs::symlink_metadata` should be used instead.

**Comment by crides** [comment]
I hope this is **really** fixed in 2.1.11, as 2.1.9 ate my stuff again. And it's much worse this time.

**Comment by vks** [comment]
@crides I believe it is fixed now, but please look at the code yourself. It uses `symlink_metadata` instead of `metadata`, so symlink detection should work now.
