### ISSUE TITLE
Inlcusion in winget (Windows Package Manager)

### ISSUE THREAD

**Issue by asilentdreamer** [Byron/dua-cli#255]
I have opened a request for including dua-cli in winget with the tentative package name `byron.dua-cli`. It would be great if there are any  additional inputs there with changes if required.

Link to request for inclusion: https://github.com/microsoft/winget-pkgs/issues/167128

**Comment by Dragon1573** [comment]
@Byron, sorry to ping you here. 🙏🏼

Are you willing to integrate [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser) to your [GitHub Workflows](https://github.com/Byron/dua-cli/actions/workflows/release.yml)? It's better the publisher & author takes full control of their manifests in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs).

Enabling this integration requires the package already available in the repository. I'm currently working on this "very first" manifest version.

**Comment by Byron** [comment]
Thanks a lot for your help with this!

I'd be happy to integrate it into the GitHub CI, as it's preferable to control what goes into a package if possible. However, I'd definitely appreciate if all I had to do was to setup an account somewhere and add the secret to the project's CI. Maybe that's possible, but I'd need your guidance in any case.

**Comment by Dragon1573** [comment]
The "very first" manifest of this package is successfully merged :tada:

I can help creating pull request for integrating _WinGet Releaser_ into the release workflow. :heart:

**Comment by Byron** [comment]
> I can help creating pull request for integrating _WinGet Releaser_ into the release workflow. ❤️

Yes, I'd definitely appreciate that.
