### ISSUE TITLE
dua doesn't write "DeletionDate" field in .trashinfo files

### ISSUE THREAD

**Issue by 5121f** [Byron/dua-cli#265]
Seems like dua doesn't write "DeletionDate" field in .trashinfo files. Some other tools uses this field. In my case gtrash (app for manage trashcan) shows me warnings related to files moved to trash using dua.

**Comment by Byron** [comment]
Thanks for letting me know!

I have created a [new release](https://github.com/Byron/dua-cli/releases/tag/v2.29.3) with a more recent version of the [`trash`](https://crates.io/crates/trash) crate. Maybe that improves the issue.

If not, please reopen the issue there as that's what `dua` uses to put items into the trash. Thank you.
