### ISSUE TITLE
dua still doesn't write "DeletionDate" field in .trashinfo files

### ISSUE THREAD

**Issue by 5121f** [Byron/dua-cli#268]
Reopen of #265

dua still doesn't write "DeletionDate" field in .trashinfo files.

I looked at the code, checked and found out that the enable of the "chrono" feature for the `trash` crate would solve the problem.

(IMHO `trash` crate should do this by default)

**Comment by Byron** [comment]
Thanks for the research. There is a [new release](https://github.com/Byron/dua-cli/releases/tag/v2.29.4) to test now.

**Comment by 5121f** [comment]
Yes. New release solved the problem.

Thanks for fast response and great app!
