### ISSUE TITLE
Mangled output in interactive mode

### ISSUE THREAD

**Issue by shishkin** [Byron/dua-cli#272]
Hi, I really like dua for quickly locating and purging large directories!

Just noticed that on my system (MacOS, Wezterm), the output in the interactive mode during scanning gets mangled when system errors get appended. Maybe TUI is not taking that output into account and is not redrawing over it. The messages I see look like these:

```
nfs server OrbStack:/OrbStack: not responding
nfs server OrbStack:/OrbStack: is alive again
nfs server OrbStack:/OrbStack: resource temporarily unavailable (jukebox)
nfs server OrbStack:/OrbStack: is alive again
```

After scanning it takes some cursor moving to redraw the TUI output, but it still remains mangled in some places.

**Comment by Byron** [comment]
This isn't anything that `dua` can fix, unfortunately. It's a background program that is connected to the terminal in question, which gets triggered by `dua`'s activity.

This might be something that OrbStack can affect.
