### ISSUE TITLE
No license files in failure-tools crate

### ISSUE THREAD

**Issue by tim77** [Byron/dua-cli#29]
Please add license files. Maybe they are exist but i cant find a repo. :)
https://crates.io/crates/failure-tools points me there https://github.com/share-secrets-safely/cli

**Comment by ignatenkobrain** [comment]
@Byron-TW @Byron ping?

**Comment by Byron** [comment]
Sorry for the late reply, admittedly that one flew under my radar. I had a look, and was shocked to see that apparently I didn't keep the code, or can't find it myself! By the looks of it, there is no repository, and there is no such library in the history Share Secrets Safely either. The code is from there, but the library 'failure-tools' seems to have vanished.

I plan to fix this in the coming days by publishing a new release based on the latest code from crates.io.

**Comment by ignatenkobrain** [comment]
@Byron thanks a lot! Once it is there, we'll package dua-cli for Fedora in the official repos!

**Comment by Byron** [comment]
Alright, I have pushed of `failure-tools` into [its own repository](https://github.com/Byron/failure-tools) and pushed [a new version](https://crates.io/crates/failure-tools).

Please let me know if you need `dua-cli` to be re-released with updated dependencies, or if there is anything else that I can help you with :)!

Also CC: @jessegrosjean , the author of `jwalk`, the heart of `dua-cli`.
