### ISSUE TITLE
Could use -x flag

### ISSUE THREAD

**Issue by BartMassey** [Byron/dua-cli#3]
Would be really nice if `dua` would support `-x` for "don't cross filesystem boundaries"…

**Comment by Byron-TW** [comment]
Thanks for the hint - it's something I can imagine for 2.X.

**Comment by SerialVelocity** [comment]
This would be very useful. Trying to figure out what is taking up the space in your root filesystem is pretty difficult without this :)

**Comment by BartMassey** [comment]
Thanks!
