### ISSUE TITLE
Are there any plans for adding binary release?

### ISSUE THREAD

**Issue by wfxr** [Byron/dua-cli#32]
@Byron This tool is awesome. Thanks for your brillient work!

Currently we have to install the entire set of rust SDK to compile and install it. This is a bit cumbersome for non-rust users. This also prevents us from using it on some server environment.

So would you consider adding support for binary releases?

**Comment by Byron** [comment]
Thanks for the kudos, it's always nice to hear that a tool scratching ones itch is useful to others as well!

I totally understand your issue and would be happy to host a binary built on your linux system on Github, and I would throw in the binary for OSX. This would fix the issue immediately and for the time being.

Once there is an update to this crate, I may consider automating it.
What do you think?

**Comment by wfxr** [comment]
@Byron Great! Looking forward to your updates.

**Comment by Byron** [comment]
@wfxr That's great! What I tried to say is: Which linux distribution do you run `dua` on? I think I should be able to compile a version myself and upload it to releases manually.

**Comment by Byron** [comment]
Anyhow, I just added [releases](https://github.com/Byron/dua-cli/releases/tag/2.1.13), the MUSL one should work for most linux distributions out there.

**Comment by wfxr** [comment]
@Byron Sorry for the late reply. The MUSL version works for me. Thank you!

**Comment by gabrielmagno** [comment]
Hi @Byron. Awesome tool!

I was wondering if you could provide pre-compiled binaries in the releases in GitHub. This would make dua's utilization as simple as downloading a file and running it, no rust tools and compiling time necessary.

I am not familiar with rust programming automation and deploy tools, but I can see that some Rust projects do that (not sure how):
- `rg`: https://github.com/BurntSushi/ripgrep/releases
- `bat`: https://github.com/sharkdp/bat/releases
- `xsv`: https://github.com/BurntSushi/xsv/releases
- `fzf`: https://github.com/junegunn/fzf-bin/releases (exclusive branch only for binary releases)

Thank you very much!

**Comment by Byron** [comment]
Thanks for the request :) - just yesterday I created a Rust github action for the very first time. Thus far I dodged it as I felt there were other priorities, but now I realise why people embrace GitHub actions.

So I will use this ticket to track progress, and since I probably 'just' have to do some copy-paste, it should be available soonish.

**Comment by Byron** [comment]
From now on, there will be binaries for [every release](https://github.com/Byron/dua-cli/releases).
The [latest one](https://github.com/Byron/dua-cli/releases/tag/v2.3.8) just doubles the `dua interactive` performance for me, in case you want to have a look.
