### ISSUE TITLE
Ctrl + r doesn't work in interactive mode

### ISSUE THREAD

**Issue by ms747** [Byron/dua-cli#33]
As the title suggests after marking files, Ctrl + r has no effects (deleting). 
Tried both release version and cargo compiled version.

**Comment by Byron** [comment]
Does it keep being an issue if you follow these steps?

Select something with **space** or **d*…
<img width="1020" alt="Screenshot 2020-02-22 at 09 46 08" src="https://user-images.githubusercontent.com/63622/75084025-3ef5ca80-5558-11ea-81da-0659a661761f.png">
…then hit the **<tab>** key…
<img width="1114" alt="Screenshot 2020-02-22 at 09 46 19" src="https://user-images.githubusercontent.com/63622/75084036-4d43e680-5558-11ea-9df9-33e623bfd8c0.png">
…and now hitting `ctrl+r` will work as advertised.

The process is intentionally forcing the user to perform multiple steps to make accidental deletion less likely.

If this doesn't fix your issue it may be a bug, which is when you can provide clear steps to reproduce it and we can reopen the issue.

Hope that helps.

**Comment by Byron** [comment]
Yes, I think that could be a simple improvement with a lot of potential to reduce initial confusion on how to delete files.

Would you like to help with that? It's `src/interactive/widgets/help.rs` that would need an adjustment.

**Comment by sommerper** [comment]
@Byron Sure, I'll do it. (Just not with my work account from above) ;-)

**Comment by sommerper** [comment]
@Byron I'd like to commit a branch for review.
