### ISSUE TITLE
No license files in tui-react crate

### ISSUE THREAD

**Issue by tim77** [Byron/dua-cli#38]
Terribly sorry, but i found only now this -- we need to add license files in `tui-react` crate as well.

And no license file at `dua-cli` crate (ver `2.3.1`).

**Comment by ignatenkobrain** [comment]
For `tui-react` you need to copy or symlink LICENSE file into a subfolder. And for dua-cli, it is due to https://github.com/Byron/dua-cli/blob/master/Cargo.toml#L6

**Comment by Byron** [comment]
Thanks so much for letting me know :)! Please have a look at the latest releases of both crates, and you should find a LICENSE file within the crate.
