### ISSUE TITLE
Some tests not passed

### ISSUE THREAD

**Issue by tim77** [Byron/dua-cli#39]
Hello. Some tests not passed on Fedora. Maybe it is safe to disable them? Would appreciate any tip.

```rust
failures:
    interactive::app_test::journeys_readonly::simple_user_journey_read_only
    interactive::app_test::journeys_with_writes::basic_user_journey_with_deletion
    interactive::app_test::unit::it_can_handle_ending_traversal_reaching_top_but_skipping_levels
    interactive::app_test::unit::it_can_handle_ending_traversal_without_reaching_the_top

test result: FAILED. 1 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

- OS: `Fedora Rawhide (33)`
- GCC: `10`
- [Full build log](https://download.copr.fedorainfracloud.org/results/atim/rust-crates/fedora-rawhide-x86_64/01251153-rust-dua-cli/builder-live.log.gz)

**Comment by ignatenkobrain** [comment]
I believe all of them fail since the tests data are not included on crates.io archive.

Also, knowing GCC version is entirely useless since this is Rust application.

**Comment by Byron** [comment]
Yes, indeed, they are not included in the crate. As I am very conscious about keeping crates small, I only include what's needed to build and use, not to test.

Something you could do is to check the travis badge/results for a particular commit - it runs all the tests and I only release if CI is green.

In this particular case, it appears tests weigh a lot, so I would like to avoid packaging them.

<img width="200" alt="Screenshot 2020-02-25 at 08 27 06" src="https://user-images.githubusercontent.com/63622/75203250-9e4a1980-57a8-11ea-9c52-d911489630d5.png">

What do you think?

**Comment by ignatenkobrain** [comment]
Well, it is not that simple :)

When we build apps in Fedora, we use our crates (sometimes might not match 1:1 with crates.io), also the compiler version can be different than you tested and so on and so forth.

But of course, I agree that adding another 2 megabytes just because of tests does not make sense. Since you do tags on github, we will probably just download tests from them :)

**Comment by ignatenkobrain** [comment]
Oh, and also of course we do builds on armv7hl, aarch64, ppc64le, s390x.. Pretty sure you don't have most of those in the CI :)

**Comment by Byron** [comment]
I understand now :). And I love that you are able to download the archives GitHub provides to fill in the blanks, or build from GitHub source right away.

Hence I close this issue, as no action is required of me.
