### ISSUE TITLE
Pressing "d" twice on "left pane" adds and then removes item from queue

### ISSUE THREAD

**Issue by ignatenkobrain** [Byron/dua-cli#45]
I'm not sure if the title is clear, but when I go through list of folders/files and press `d` on already added file to removal's queue, causing that directory/file to disappear.

**Comment by Byron** [comment]
That's the intended behaviour, `d` toggles the current item and moves the selection down one item. Hitting spacebar only toggles the current item. In any case, the item is toggled.
There currently is no way to 'only add' items for removal.

Is this a feature you would like to see?

**Comment by ignatenkobrain** [comment]
I'd like to have `d` to not toggle item, but queue for deletion and move down and keep the rest as-is. I think this would be more intuitive :)

**Comment by Byron** [comment]
Even though I didn't try it, I happily take your word for it, and imagine `d` becoming a 'select for deletion' only, whereas `x` could become what `d` was before. Possibly `x` could become a 'deselect' only, that is the opposite of the _new_ `d`.

**Comment by Byron** [comment]
In order not to change existing behaviour, `d` behaves as it always did, and `x` behaves as suggested here: it marks entries for deletion only.
