### ISSUE TITLE
dua reacts very slowly to <Ctrl+C> when in scanning mode

### ISSUE THREAD

**Issue by ghuls** [Byron/dua-cli#47]
dua reacts very slowly (takes several minutes) to <Ctrl+C> when in scanning mode.

This happens at least when directories contain TBs of data and milions of files.

**Comment by Byron** [comment]
Thanks for reporting! I would argue that it does not respond at all while it is scanning. Dua itself is fully synchronous, and will either process keyboard input or scan the file system while providing occasional updates.

When scanning large amounts of data that can take dua minutes even, this certainly is not acceptable anymore. 

I can imagine fixing that soonish, which would come with the additional benefit of allowing to navigate the tree structure while files are parsed. The latter might happen in a second step though.

**Comment by ghuls** [comment]
Thanks a lot. It works great now.
