### ISSUE TITLE
`cargo test` fails with 2.6.1 on Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [Byron/dua-cli#54]
2.6.0 was just fine.

```rust
     Running `/usr/bin/rustc --crate-name dua --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C opt-level=3 --test -C metadata=228cdbfea33370d8 -C extra-filename=-228cdbfea33370d8 --out-dir /builddir/build/BUILD/dua-cli-2.6.1/target/release/deps -L dependency=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps --extern atty=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libatty-efc19819d1e9ac80.rlib --extern byte_unit=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libbyte_unit-9917bd0f9c97097c.rlib --extern failure=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libfailure-e093753d2ec7c7c4.rlib --extern failure_tools=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libfailure_tools-30b5aa0b3d43fa94.rlib --extern filesize=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libfilesize-bc04f6e10858ccda.rlib --extern flume=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libflume-1e130c8f2ab3217a.rlib --extern itertools=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libitertools-8e2ba6bcd515d3d0.rlib --extern jwalk=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libjwalk-abacfb9894dbf2f7.rlib --extern log=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/liblog-4f78b14c47d616f3.rlib --extern num_cpus=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libnum_cpus-a99fc62929d3f35a.rlib --extern open=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libopen-5b63bcbf351a5fce.rlib --extern petgraph=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libpetgraph-7caee99cf66647d3.rlib --extern pretty_assertions=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libpretty_assertions-053e62e3fbe5376b.rlib --extern structopt=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libstructopt-2be276fcf633a1ba.rlib --extern termion=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libtermion-84f1efa561a3024a.rlib --extern tui=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libtui-cea60341ec7a6847.rlib --extern tui_react=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libtui_react-9232341d273ced1f.rlib --extern unicode_segmentation=/builddir/build/BUILD/dua-cli-2.6.1/target/release/deps/libunicode_segmentation-6a1ece1fa7c08bb8.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 --cap-lints=warn`
error[E0583]: file not found for module `app_test`
  --> src/interactive/mod.rs:35:5
   |
35 | mod app_test;
   |     ^^^^^^^^
   |
```

**Comment by ignatenkobrain** [comment]
I believe that the issue started to happen because of https://github.com/Byron/dua-cli/commit/ca2dc43b5aa1c0a2f025a697c9956f29d1bf0fe4

**Comment by ignatenkobrain** [comment]
I'm sure that running tests on Fedora when building dua-cli is very useful so I think that saving few kilobytes is not worth removing this testing.

**Comment by Byron** [comment]
Thanks for reporting and finding the commit that caused the issue.

Would it be possible to see the build scripts and how they work?
The reason I am asking is that maybe, these could be changed to clone the source code instead and checkout the tag of the new version, and test and build from there instead.

That way, crate packages can be optimized to be minimal in size while providing what you need to build and run, and to look good on crates.io/lib.rs. Everything else is exclusively in the git repository.

What do you think?

**Comment by ignatenkobrain** [comment]
Here's the build script: https://src.fedoraproject.org/rpms/rust-dua-cli/blob/master/f/rust-dua-cli.spec

We can use additional source to the one from crates.io but we generally prefer not to do so because that means we are not necessarily testing what's published on crates.io.

Also it basically means that we will have to prepare those sources by hand because we need to only include missing files that means every time run some command that will prepare just missing sources. And this won't be possible to automate.

I also did not check if the fixtures are needed for those tests to work (aka `tests` directory), so if it is - just close this bug and I'll manage second source, shouldn't be hard.

**Comment by ignatenkobrain** [comment]
yeah, seems that fixtures are needed, so just scratch that.
