### ISSUE TITLE
support showing timestamps for files/dirs

### ISSUE THREAD

**Issue by juhp** [Byron/dua-cli#67]
It is often useful to know how old a file or directory is when deciding if it can be deleted say.
It would be a nice feature to add to dua in my opinion: I don't think they need be cached.

**Comment by Byron** [comment]
I agree, this part of the metadata wouldn't have to be stored for all files it iterates. Instead it could be extracted from the meta-data that is queried each time a level of files is displayed. This is currently used to indicate missing files in red (_useful to see they have been deleted already_).

It would be worth figuring out which timestamp exactly should be chosen, last modified time, or creation time. My intuition is modified time.

**Comment by juhp** [comment]
Any pointers or suggestions how to tackle this?  I am mostly a rust newbie alas,
but I don't mind at least trying to poke around a bit to see what I can find out.

**Comment by Byron** [comment]
The entries panel (the one you are interested in) is [drawn here](https://github.com/Byron/dua-cli/blob/69a2490844d87c09cd5cc51da49e3cd87a03c35a/src/interactive/widgets/entries.rs#L97-L167).

Currently it only knows about the [existence of an entry](https://github.com/Byron/dua-cli/blob/69a2490844d87c09cd5cc51da49e3cd87a03c35a/src/interactive/widgets/entries.rs#L102), but that could be [extended here](https://github.com/Byron/dua-cli/blob/69a2490844d87c09cd5cc51da49e3cd87a03c35a/src/interactive/widgets/entries.rs#L102).

The trickier bits should be around drawing the dates correctly, but that is usually a matter of experimentation with `cargo run -- i`.

If you have more questions or trouble, please feel free to post here for some help.

**Comment by gosuwachu** [comment]
IMHO this is now done.

**Comment by Byron** [comment]
Agreed 👍.
