### ISSUE TITLE
install.sh on Windows not working

### ISSUE THREAD

**Issue by ponchofiesta** [Byron/dua-cli#69]
- Windows 10 1809
- Having MSYS2 installed
- Open cmd:
```
sh install.sh --git byron/dua-cli --crate dua
install.sh: GitHub repository: https://github.com/byron/dua-cli
install.sh: Crate: dua
install.sh: Tag: latest (v2.10.3)
install.sh: Target: x86_64-pc-windows-msvc
install.sh: Installing to: /c/Users/XXX/.cargo/bin
install.sh: Downloading: https://github.com/byron/dua-cli/releases/download/v2.10.3/dua-v2.10.3-x86_64-pc-windows-msvc.tar.gz
tar.exe: Error opening archive: Failed to open '\\.\tape0'
(23) Failed writing body
```

**Comment by Byron** [comment]
Thanks for letting me know. It seems the script assumes `.tar.gz`, whereas the github action produces a zip file (`dua-v2.10.3-x86_64-pc-windows-msvc.zip`).

In theory, if a `.tar.gz` file is provided, it should work out of the box. Just now I have added such a file to the latest release. If you could try again to verify this is working, I could adjust the build script to produce a `.tar.gz` file as well.

Thanks for your help

**Comment by ponchofiesta** [comment]
Hi,
still not working. The problem is the temp path:
```bash
td=$(mktemp -d || mktemp -d -t tmp)
# -> /tmp/... not working on Windows
```

This mktemp executable is from MSYS2. On a typical Windows this should fail. I assume tar would than extract it to the working directory?
I think it would be better to provide a cmd or Powershell script for Windows.

**Comment by Byron** [comment]
I have a feeling that [`install.sh`](https://github.com/japaric/trust) wasn't really created with Windows in mind. By the looks of it, the script isn't even meant to be used on windows, and a powershell/cmd version of it is not provided either.

Maybe contributing to `trust` is the way to get this to work, currently I [don't think there is an issue](https://github.com/japaric/trust/issues?q=is%3Aissue+is%3Aopen+windows) for this either.

**Comment by ponchofiesta** [comment]
I searched for projects using a install.sh and what they are doing on Windows. Rustup and wasm-pack use an exe (written in Rust). Other projects do not provide a solution for Windows. Maybe it's not that easy. But if it's not working, you should remove this from the readme, i think.

I used the binary now. cargo install didn't work too. Error was something like feature not supported in stable toolchain or something.

**Comment by Byron** [comment]
Thanks for looking into it. I agree, there doesn't seem to be an easy way right now (except for using `cargo +nightly install dua-cli`, and I have update the README to reflect that.

This seems better than waiting for better installation scripts to come along as it helps windows users by not misleading them.
