### ISSUE TITLE
[Suggestion] Show progress while analyzing

### ISSUE THREAD

**Issue by Zeex** [Byron/dua-cli#70]
Suggestion:

Make `dua` display a progress bar or some kind of activity indicator while it's analyzing the disk, so that the user realizes that the program is doing some work and didn't hang. 

When I first ran it (on Windows) I thought that it's stuck, but it turned out that dua was actually working, it just took a while to complete (a few minutes for my system disk).

**Comment by Byron** [comment]
Thanks for reporting!

I just had a look and noticed that besides a changing amount of Entries in the bottom of the screen there is indeed no indicator of it doing anything. Of course, the amount of directories and their sizes usually change, but sometimes that's not very obvious either.

There was an issue with a red message not showing up unless one would navigate the directory tree while it's scanning, which has just been fixed. Now the GUI shows up like this:

![Screenshot 2020-11-02 at 09 05 11](https://user-images.githubusercontent.com/63622/97820741-87ba7180-1cea-11eb-9ca6-c5c0fddedfe0.png)

This is probably as good as it gets if I do it, but if you have other ideas on how to indicate progress please feel free to state them here and maybe someone contributes the implementation.

**Comment by Zeex** [comment]
Sorry, I'm dumb, I didn't notice that I was starting dua in non-interactive mode. In interactive mode it looks much nicer. Thank you.
