### ISSUE TITLE
--version or -V doesn't tell the version

### ISSUE THREAD

**Issue by mburr-precor** [Byron/dua-cli#76]
I installed `dua` yesterday and tried to get the version number for another (now closed) issue, but found that it wouldn't tell me:

```
mburr@mint-19:~$ ~/.cargo/bin/dua --version
dua 
mburr@mint-19:~$ ~/.cargo/bin/dua -V
dua 
```

I installed `dua` like so:

```
curl -LSfs https://raw.githubusercontent.com/byron/dua-cli/master/ci/install.sh |     sh -s -- --git byron/dua-cli --target x86_64-unknown-linux-musl --crate dua
```

Running on Linux Mint 19.3

**Comment by Byron** [comment]
Thanks for letting me know - fixed with 2.10.10.
