### ISSUE TITLE
Goto the top of the list in interactive mode automatically after finished

### ISSUE THREAD

**Issue by c02y** [Byron/dua-cli#77]
`dua v2.10.7-1` installed from Manjaro repo or `v2.10.10` downloaded from release page

Whenever I use `dua` in interactive mode for a directory, the point is never located in the top item in the list when `dua` is loaded

![Peek 2021-02-08 23-44](https://user-images.githubusercontent.com/2135996/107243404-ee78c500-6a67-11eb-90b1-9e47ffd5e5b0.gif)

**Comment by Byron** [comment]
Thanks a lot for letting me know! It's indeed expected behaviour as the traversal is fully interactive. Thus it places the selection at the first entry it sees, and keeps it there allowing the user to move between the entries.

This certainly has the side-effect that it appears the selection is off.
That said, I wonder what could be done to make the behaviour less surprising without removing a legitimate feature. Your feedback is appreciated.

**Comment by c02y** [comment]
Could you please provide an option that when I set it, it will go to the top of the list when dua is loaded?

**Comment by Byron** [comment]
What about detecting whether a user has provided inputs already during traversal and if not the case, keep the first entry selected. Otherwise, don't adjust selection anymore.
That way it's probably the expected behaviour for everyone.

**Comment by c02y** [comment]
Actually, I'm using an alias for ```dua -f binary i $argv/*```(I'm using fish shell), if no input is provided, it will automatically use the current directory as the input, whether an input is provided or not, an argument will be given to dua command.

There is another weird design in `dua`, I add an `*` at the end of my alias since I noticed that when I use something like `dua i /` or `dua /`, it will not list the content but only the directory `/` itself, this is different from `ncdu` or `gdu` I've used which will list the content of the input directory instead of just the input directory itself since it will get `Total disk usage: xxx GB` at the bottom of dua screen anyway, maybe you can provide an option that when input is given, get the size of the directory only, otherwise, get the list of the content.

Another thing, I believe the bindings to directly jump to the top/bottom of the list should be provided too.

**Comment by Byron** [comment]
> There is another weird design in dua, I add an * at the end of my alias since I noticed that when I use something like dua i / or dua /, it will not list the content but only the directory / itself.

That's indeed a feature, even though it's certainly debatable if it's a desirable one. I myself often wish it always expand the only given path similarly to what it does if no path argument is given at all.

> Another thing is, I believe the bindings to directly jump to the top/bottom of the list should be provided too.

Agreed.

As the points above are different change requests, would you mind dropping them into their own issue?

**Comment by Byron** [comment]
I am closing this issue as I believe the fix was sufficiently well implemented.

Please take a look.

**Comment by Byron** [comment]
v2.11.0 was released containing [the changes](https://github.com/Byron/dua-cli/blob/master/CHANGELOG.md#v2110).
