### ISSUE TITLE
[Feature request]Add an option, do not sort the result

### ISSUE THREAD

**Issue by c02y** [Byron/dua-cli#83]
When I use dua to count the size of multiple targets, since sometimes the order of the targets' names is more important to me, I do not want dua to sort the size of the result but keep the order of the names passed as arguments to the dua command.

**Comment by Byron** [comment]
For the `aggregate` mode this already exists. It can be enabled with `dua a --no-sort <roots>`.
That's not a thing in interactive mode though, is this what this request is referring to?

**Comment by c02y** [comment]
Oh, sorry, didn't notice the subcommand have a help page
