### ISSUE TITLE
Why is `dua aggregate --apparent-size ...` not valid?

### ISSUE THREAD

**Issue by KSXGitHub** [Byron/dua-cli#91]
The valid command is `dua --apparent-size aggregate ...`, which is weird.

**Comment by Byron** [comment]
Could you replace the word 'weird' with a description of the expected behaviour? That should make this issue actionable. Thank you.

**Comment by KSXGitHub** [comment]
@Byron Dude, that's just my personal opinion, no needs to be passive-aggressive. Anyway, can you consider making `dua aggregate --apparent-size ...` valid?
