### ISSUE TITLE
EntryData name allocation

### ISSUE THREAD

**Issue by jessegrosjean** [Byron/dua-cli#92]
I have no idea if this makes a real difference, but I just noticed that I think you are allocating when you copy from jwalk Entry to your EntryData.name PathBuf. I also notice that the root entry data gets the full path and I suppose you must be combining things and building paths somewhere.

All that to say that "maybe" you could gain performance by just making EntryData wrap a jwalk entry? The entries are fairly lightweight I think... they don't each contain full path. Instead only Folder entries have path... leaf children share an Arc of that path.

**Comment by Byron** [comment]
Thanks for taking a look!

I checked once again this line which I think you are referring to…

https://github.com/Byron/dua-cli/blob/d381c6caed1fd404d7a11c1f581abdba749b7a20/src/traverse.rs#L111

…which transforms and moves an `OsString` into a `PathBuf` - this happens without any allocation as it moves out of the `jwalk` Entry.

```Rust
#[stable(feature = "rust1", since = "1.0.0")]
impl From<OsString> for PathBuf {
    /// Converts a `OsString` into a `PathBuf`
    ///
    /// This conversion does not allocate or copy memory.
    #[inline]
    fn from(s: OsString) -> PathBuf {
        PathBuf { inner: s }
    }
}
```

The `EntryData` also doesn't keep the full path, each of them is only their name (without interning, admittedly) and should really be as small in memory as possible as there are plenty of them in interactive mode. 

>  I also notice that the root entry data gets the full path and I suppose you must be combining things and building paths somewhere.

That's exactly what's happening. With this high memory usage isn't a problem even for entire disk states and thus far strikes a good balance between simplicity and cost.

> I have no idea if this makes a real difference […]

A better place to test actual overhead is probably the [`traverse`] code as it's not doing anything but aggregating a few integers. It's very close to the `jwalk` `du` example in terms of overhead.

That said, from my experience anything that `dua` does right now pretty much pales in comparison to the cost of the fs traversal and the fs syscalls, and the real win here would only be a general solution for the 'M1 problem' at least on my specific machine :D.

My feeling is that `jwalk` is actually pretty optimal already and these usertimes might even be inflated as they might be coming from these 4 low-power cores which probably take 10 times longer to do anything. They might contribute disproportionally to the programs userland time.

[traverse]: https://github.com/Byron/dua-cli/blob/ac604b35c0b80fa6b380cc395a95bf0a5d1d196d/src/aggregate.rs#L63

Please feel free to close this issue unless there is anything else I could take a look at.

**Comment by jessegrosjean** [comment]
Ehh, rust is magic... I know about restructuring, but I thought it had to be a manual operation. I didn't know it could happen automatically in that case. Know I know... though I think I'm very likely to forget again.
